/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InteractionsRouteImport } from './routes/interactions'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as GoalkeepersRouteImport } from './routes/goalkeepers'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemUsersRouteImport } from './routes/system.users'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as GoalkeepersGkIdRouteImport } from './routes/goalkeepers.$gkId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsRoute = InteractionsRouteImport.update({
  id: '/interactions',
  path: '/interactions',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalkeepersRoute = GoalkeepersRouteImport.update({
  id: '/goalkeepers',
  path: '/goalkeepers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersRoute = SystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)
const GoalkeepersGkIdRoute = GoalkeepersGkIdRouteImport.update({
  id: '/$gkId',
  path: '/$gkId',
  getParentRoute: () => GoalkeepersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/users': typeof SystemUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/users': typeof SystemUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/audit': typeof AuditRoute
  '/calendar': typeof CalendarRoute
  '/executive': typeof ExecutiveRoute
  '/goalkeepers': typeof GoalkeepersRouteWithChildren
  '/intelligence': typeof IntelligenceRoute
  '/interactions': typeof InteractionsRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/mentors': typeof MentorsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/goalkeepers/$gkId': typeof GoalkeepersGkIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/system/users': typeof SystemUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/intelligence'
    | '/interactions'
    | '/login'
    | '/media'
    | '/mentors'
    | '/reports'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/intelligence'
    | '/interactions'
    | '/login'
    | '/media'
    | '/mentors'
    | '/reports'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/users'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/audit'
    | '/calendar'
    | '/executive'
    | '/goalkeepers'
    | '/intelligence'
    | '/interactions'
    | '/login'
    | '/media'
    | '/mentors'
    | '/reports'
    | '/goalkeepers/$gkId'
    | '/reports/$reportId'
    | '/system/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuditRoute: typeof AuditRoute
  CalendarRoute: typeof CalendarRoute
  ExecutiveRoute: typeof ExecutiveRoute
  GoalkeepersRoute: typeof GoalkeepersRouteWithChildren
  IntelligenceRoute: typeof IntelligenceRoute
  InteractionsRoute: typeof InteractionsRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  MentorsRoute: typeof MentorsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  SystemUsersRoute: typeof SystemUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions': {
      id: '/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof InteractionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goalkeepers': {
      id: '/goalkeepers'
      path: '/goalkeepers'
      fullPath: '/goalkeepers'
      preLoaderRoute: typeof GoalkeepersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users': {
      id: '/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/goalkeepers/$gkId': {
      id: '/goalkeepers/$gkId'
      path: '/$gkId'
      fullPath: '/goalkeepers/$gkId'
      preLoaderRoute: typeof GoalkeepersGkIdRouteImport
      parentRoute: typeof GoalkeepersRoute
    }
  }
}

interface GoalkeepersRouteChildren {
  GoalkeepersGkIdRoute: typeof GoalkeepersGkIdRoute
}

const GoalkeepersRouteChildren: GoalkeepersRouteChildren = {
  GoalkeepersGkIdRoute: GoalkeepersGkIdRoute,
}

const GoalkeepersRouteWithChildren = GoalkeepersRoute._addFileChildren(
  GoalkeepersRouteChildren,
)

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuditRoute: AuditRoute,
  CalendarRoute: CalendarRoute,
  ExecutiveRoute: ExecutiveRoute,
  GoalkeepersRoute: GoalkeepersRouteWithChildren,
  IntelligenceRoute: IntelligenceRoute,
  InteractionsRoute: InteractionsRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  MentorsRoute: MentorsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  SystemUsersRoute: SystemUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
